In [1]:
import json
import os 
from google.cloud import bigquery
import pandas as pd
import sqlalchemy

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "./staging-udts-01-26edf3092bf7.json"

In [2]:
# client = bigquery.Client(project="staging-udts-01")
# sql = "SELECT * FROM `staging-udts-01.test_spa_connection.course` LIMIT 20"
# rows = client.query(sql).result()
# data = rows.to_dataframe()
# data.head()

In [ ]:
# schema = rows.schema
# with open('schema.jsonl','w', encoding='utf-8') as f:
#     for col in schema:
#         f.write(json.dumps(col.to_api_repr()) + '\n')

In [2]:
data = pd.read_csv('test_spa_course.csv')
data.head()

,student_id,cohort,cohort_term,academic_year,academic_term,institution_id_type,institution_id,first_name,middle_name,last_name,...,num_credits_earned_cumsum,num_courses_course_type_cc,num_courses_course_type_cd,num_courses_course_type_el,num_courses_course_type_ab,num_courses_course_type_ge,num_courses_course_type_nc,num_courses_course_type_o,frac_courses_course_type_cc,frac_courses_course_type_cd
0,506849078,2020-21,Fall,2020-21,Winter,OPEID,1,AARON,NaN,BAYLOR,...,28.0,1,0,1,0,2,0,2,0.17,0.00
1,506849078,2020-21,Fall,2022-23,Fall,OPEID,1,AARON,NaN,BAYLOR,...,54.0,1,0,1,1,0,0,1,0.17,0.00
2,506849078,2020-21,Fall,2022-23,Fall,OPEID,1,AARON,NaN,BAYLOR,...,54.0,1,0,1,1,0,0,1,0.17,0.00
3,506849078,2020-21,Fall,2021-22,Fall,OPEID,1,AARON,NaN,BAYLOR,...,41.0,0,2,0,0,0,1,2,0.00,0.33
4,506849078,2020-21,Fall,2020-21,Winter,OPEID,1,AARON,NaN,BAYLOR,...,28.0,1,0,1,0,2,0,2,0.17,0.00

In [2]:
schema = pd.read_json("schema.jsonl", lines=True)
schema

                           name     type      mode
0                    student_id  INTEGER  NULLABLE
1                        cohort   STRING  NULLABLE
2                   cohort_term   STRING  NULLABLE
3                 academic_year   STRING  NULLABLE
4                 academic_term   STRING  NULLABLE
..                          ...      ...       ...
77   num_courses_course_type_ge  INTEGER  NULLABLE
78   num_courses_course_type_nc  INTEGER  NULLABLE
79    num_courses_course_type_o  INTEGER  NULLABLE
80  frac_courses_course_type_cc    FLOAT  NULLABLE
81  frac_courses_course_type_cd    FLOAT  NULLABLE

[82 rows x 3 columns]

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 422574 entries, 0 to 422573
Data columns (total 82 columns):
 #   Column                                               Non-Null Count   Dtype
---  ------                                               --------------   -----
 0   student_id                                           422574 non-null  int64
 1   cohort                                               422574 non-null  str
 2   cohort_term                                          422574 non-null  str
 3   academic_year                                        422574 non-null  str
 4   academic_term                                        422574 non-null  str
 5   institution_id_type                                  422574 non-null  str
 6   institution_id                                       422574 non-null  int64
 7   first_name                                           422534 non-null  str
 8   middle_name                                          390319 non-null  str
 9   last_name                                            422574 non-null  str
 10  suffix                                               0 non-null       float64
 11  current_street_1                                     422574 non-null  str
 12  current_street_2                                     0 non-null       float64
 13  current_city                                         422574 non-null  str
 14  current_state                                        422574 non-null  str
 15  current_zip_postal_code                              422574 non-null  int64
 16  current_country                                      422574 non-null  str
 17  date_of_birth                                        422574 non-null  int64
 18  student_phone_number                                 422574 non-null  int64
 19  pell_recipient                                       422574 non-null  str
 20  student_email                                        422574 non-null  str
 21  completedevmath                                      299136 non-null  str
 22  completedevenglish                                   298919 non-null  str
 23  transferintent                                       281895 non-null  str
 24  degree_type_sought                                   422574 non-null  str
 25  course_prefix                                        422574 non-null  str
 26  course_number                                        422574 non-null  int64
 27  section_id                                           422574 non-null  str
 28  course_name                                          422574 non-null  str
 29  course_description                                   422574 non-null  str
 30  course_type                                          422574 non-null  str
 31  math_or_english_gateway                              422574 non-null  str
 32  co_requisite_course                                  422574 non-null  bool
 33  course_begin_date                                    422574 non-null  str
 34  course_end_date                                      422574 non-null  str
 35  grade                                                422574 non-null  str
 36  number_of_credits_attempted                          422574 non-null  float64
 37  number_of_credits_earned                             422574 non-null  float64
 38  delivery_method                                      317245 non-null  str
 39  core_course                                          422574 non-null  bool
 40  core_course_type                                     140792 non-null  str
 41  core_competency_completed                            281637 non-null  object
 42  purpose_of_course_exchange                           422574 non-null  int64
 43  certification_endorsed_curriculum_program            281501 non-null  object
 44  certificate_endorsing_industry                       337875 non-null  str
 45  grade_effective_date                                 422574 non-null  int64
 46  dgi_institution_id_type                              91602 non-null   str
 47  credential_engine_identifier                         422574 non-null  str
 48  course_instructor_employment_status                  422574 non-null  str
 49  course_instructor_rank                               422574 non-null  int64
 50  foreign_language_completion                          281637 non-null  object
 51  semester_session_gpa                                 406380 non-null  float64
 52  overall_gpa                                          419936 non-null  float64
 53  num_credits_earned                                   422574 non-null  float64
 54  num_credits_attempted                                422574 non-null  float64
 55  total_combined_earned_and_transferred_credits        422574 non-null  float64
 56  course_cip                                           422574 non-null  float64
 57  race                                                 422574 non-null  str
 58  ethnicity                                            422574 non-null  str
 59  gender                                               422574 non-null  str
 60  student_age                                          422574 non-null  str
 61  enrolled_at_other_institution_s                      422574 non-null  bool
 62  enrollment_record_at_other_institution_s_state_s     0 non-null       float64
 63  enrollment_record_at_other_institution_s_carnegie_s  0 non-null       float64
 64  enrollment_record_at_other_institution_s_sector_s    0 non-null       float64
 65  enrollment_record_at_other_institution_s_locale_s    0 non-null       float64
 66  num_courses_completed                                422574 non-null  int64
 67  num_courses_grade_is_failing_or_withdrawal           422574 non-null  int64
 68  num_courses_delivery_method_f_cumfrac                422574 non-null  float64
 69  num_courses_delivery_method_o_cumfrac                422574 non-null  float64
 70  num_courses_delivery_method_h_cumfrac                422574 non-null  float64
 71  num_courses_course_grade_wwith                       422574 non-null  int64
 72  num_credits_earned_cumsum                            422574 non-null  float64
 73  num_courses_course_type_cc                           422574 non-null  int64
 74  num_courses_course_type_cd                           422574 non-null  int64
 75  num_courses_course_type_el                           422574 non-null  int64
 76  num_courses_course_type_ab                           422574 non-null  int64
 77  num_courses_course_type_ge                           422574 non-null  int64
 78  num_courses_course_type_nc                           422574 non-null  int64
 79  num_courses_course_type_o                            422574 non-null  int64
 80  frac_courses_course_type_cc                          422574 non-null  float64
 81  frac_courses_course_type_cd                          422574 non-null  float64
dtypes: bool(3), float64(20), int64(19), object(3), str(37)
memory usage: 353.2+ MB

In [ ]:
from sqlalchemy import create_engine, text

url = "postgresql://postgres:1234@localhost:5439/bq_db"
engine = create_engine(url)

In [ ]:
data.to_sql('data_table',engine, index=False, if_exists='replace')

In [ ]:
import csv
from io import StringIO

def psql_insert_copy(table, conn, keys, data_iter):
    dbapi_conn = conn.connection
    with dbapi_conn.cursor() as cur:
        buf = StringIO()
        csv.writer(buf, lineterminator="\n").writerows(data_iter)
        columns = ", ".join(f'"{k}"' for k in keys)
        sql = f'COPY {table.name} ({columns}) FROM STDIN WITH (FORMAT CSV)'
        with cur.copy(sql) as copy:
            copy.write(buf.getvalue())

data.to_sql(
    "data_table",
    engine,
    index=False,
    if_exists="replace",
    method=psql_insert_copy,
)